{% set version = "2.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jtools/jtools_{{ version }}.tar.gz
  sha256: 79a36ab47a0b57d606a32d0f8989395fb7980158c99ba5fab303e53613d497b9

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crayon
    - r-generics
    - r-ggplot2 >=3.3.0
    - r-magrittr
    - r-pander
    - r-pkgconfig
    - r-rlang >=0.3.0
    - r-tibble
  run:
    - r-base
    - r-crayon
    - r-generics
    - r-ggplot2 >=3.3.0
    - r-magrittr
    - r-pander
    - r-pkgconfig
    - r-rlang >=0.3.0
    - r-tibble

test:
  commands:
    - $R -e "library('jtools')"           # [not win]
    - "\"%R%\" -e \"library('jtools')\""  # [win]

about:
  home: https://jtools.jacob-long.com
  license: MIT
  summary: This is a collection of tools that the author (Jacob) has written for the purpose of more efficiently understanding and sharing the results of (primarily) regression analyses. There are also a number of miscellaneous functions for statistical and programming purposes. Just about everything supports models from
    the survey package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ukukas
