{% set version = "2.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jtools/jtools_{{ version }}.tar.gz
  sha256: fefc6d30fae0bd3171b4c01fc6d0849cdd95f9488c72f9423f7dfeed2ecae911

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-broom
    - r-broom.mixed
    - r-cli
    - r-generics
    - r-ggplot2 >=3.4.0
    - r-magrittr
    - r-pander
    - r-pkgconfig
    - r-rlang
    - r-sandwich
    - r-tibble
  run:
    - r-base
    - r-broom
    - r-broom.mixed
    - r-cli
    - r-generics
    - r-ggplot2 >=3.4.0
    - r-magrittr
    - r-pander
    - r-pkgconfig
    - r-rlang
    - r-sandwich
    - r-tibble

test:
  commands:
    - $R -e "library('jtools')"           # [not win]
    - "\"%R%\" -e \"library('jtools')\""  # [win]

about:
  home: https://jtools.jacob-long.com
  license: GPL-3.0-or-later
  summary: This is a collection of tools that the author (Jacob) has written for the purpose of more efficiently understanding and sharing the results of (primarily) regression analyses. There are also a number of miscellaneous functions for statistical and programming purposes. Just about everything supports models from
    the survey package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ukukas
